FROM node:20-bookworm-slim

RUN apt-get update && apt-get install -y \
  graphicsmagick \
  ghostscript \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

RUN mkdir -p uploads

CMD ["node", "worker.js"]
